version: '3.8'
services:
  dev-db:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/user/Desktop/db:/var/lib/mysql
    networks:
      - backend
    ports:
       - 3307:3306
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: social

networks:
  backend: